# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "openstack_heat"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Rob Sweet"]
  s.date = "2015-09-28"
  s.description = "API Binding for OpenStack"
  s.email = ["rob@ldg.net"]
  s.files = [
    "lib/open_stack/heat.rb",
    "lib/open_stack/heat/connection.rb",
    "lib/open_stack/heat/stack.rb",
    "lib/open_stack/heat/version.rb",
    "test/authentication_test.rb",
    "test/connection_test.rb",
    "test/exception_test.rb",
    "test/metadata_test.rb",
    "test/servers_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "https://github.com/robsweet/ruby-openstack_heat"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23.2"
  s.summary = "OpenStack Heat Ruby API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<openstack>, [">= 0"])
      s.add_runtime_dependency(%q<pry>, [">= 0"])
      s.add_runtime_dependency(%q<openstack_heat>, [">= 0"])
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<openstack>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
      s.add_dependency(%q<openstack_heat>, [">= 0"])
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<openstack>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
    s.add_dependency(%q<openstack_heat>, [">= 0"])
    s.add_dependency(%q<json>, [">= 0"])
  end
end

